"""agent-harness — a fast, lightweight harness for production AI agents.

    from agent_harness import Agent, tool

    @tool
    def order_status(order_id: str) -> str:
        '''Look up an order.

        Args:
            order_id: the order number.
        '''
        return db.lookup(order_id)

    agent = Agent("support", "Answer billing questions.", tools=[order_status])
    print(agent.run_sync("Where is order 4182?").output)

Everything is optional except the agent itself: add sub-agents, skills, memory,
MCP servers and the runtime rails as the job needs them.
"""

from __future__ import annotations

from . import modes
from .agent import Agent
from .blueprint import AgentEntry, Blueprint
from .context import ContextAssembler, ContextCompactor, estimate_tokens
from .errors import (
    AuthenticationError,
    BudgetExceeded,
    ConfigurationError,
    ContextWindowExceededError,
    GuardrailTripped,
    HarnessError,
    InvalidRequestError,
    MaxStepsExceeded,
    MCPError,
    ModelNotFoundError,
    OutputContractError,
    PermissionDenied,
    ProviderConnectionError,
    ProviderError,
    ProviderTimeoutError,
    ProviderUnavailableError,
    QuotaExceededError,
    RateLimitError,
    SessionConflict,
    StopRequested,
    ToolError,
    ToolNotFound,
    WorkflowError,
)
from .evaluation import (
    Comparison,
    EvalReport,
    Evaluator,
    Expect,
    GoldenTask,
    TaskOutcome,
    llm_judge,
)
from .guardrails import (
    POLICIES,
    AgentGuardrails,
    Check,
    CompletionContext,
    Custom,
    DetectorCheck,
    Finding,
    ForbidTools,
    Grounded,
    GroundednessDetector,
    InjectionDetector,
    LLMGuard,
    LLMVerdict,
    MaxCost,
    MaxSteps,
    MinLength,
    MustInclude,
    MustMatch,
    MustNotInclude,
    NoInjection,
    NoPII,
    NoPlaceholders,
    NoRepetition,
    NoSecrets,
    NotToxic,
    PIIDetector,
    RepetitionDetector,
    RequireCitation,
    RequireJSON,
    RequireStructured,
    RequireTools,
    SecretDetector,
    ToxicityDetector,
    Violation,
)
from .handoff import Handoff
from .harness import Harness
from .llm_providers import (
    AnthropicProvider,
    AzureFoundryProvider,
    AzureOpenAIProvider,
    BedrockProvider,
    CerebrasProvider,
    CircuitBreaker,
    CompletionRequest,
    DeepSeekProvider,
    FakeProvider,
    FireworksProvider,
    GeminiProvider,
    GoogleAuth,
    GroqProvider,
    LMStudioProvider,
    MistralProvider,
    ModelInfo,
    OllamaProvider,
    OpenAICompatibleProvider,
    OpenAIProvider,
    OpenRouterProvider,
    ParameterPlan,
    Provider,
    ProviderCheck,
    ProviderField,
    ProviderSpec,
    RetryEvent,
    RetryPolicy,
    TogetherProvider,
    ToolSchema,
    VertexGeminiProvider,
    VertexProvider,
    VLLMProvider,
    XAIProvider,
    check_llm_provider,
    describe_llm_provider,
    get_provider,
    list_llm_providers,
    ping_llm_provider,
    register_model,
    register_provider,
    tool_call,
    validate_parameters,
)
from .memory import (
    Embedder,
    FileStore,
    HashEmbedder,
    InMemoryStore,
    MemoryManager,
    MemoryRecord,
    MemoryStore,
    OrchestratorMemory,
    ProviderEmbedder,
    SemanticMemory,
    SessionMemory,
    SubAgentMemory,
    Trace,
    UserMemory,
    VectorStore,
    available_backends,
    memory_provider,
)
from .modes import Mode
from .orchestrator import Orchestrator, Plan, Review, Task
from .prompts import Prompt, PromptLibrary
from .runtime import (
    AuditEntry,
    AuditTrail,
    Budget,
    BudgetGuard,
    Checkpoint,
    Checkpointer,
    ComponentHealth,
    ConcurrencyScheduler,
    DeliverableStore,
    DurableSessionStore,
    FileSessionStore,
    Guardrails,
    HookContext,
    HookEngine,
    InMemorySessionStore,
    ModelRouter,
    PolicyGate,
    RateGuard,
    RateLimit,
    RecordingProvider,
    Replayer,
    ReplayProvider,
    ResultCache,
    RunJournal,
    ServiceHealth,
    Session,
    SessionStore,
    Span,
    StopController,
    StopState,
    Tracer,
    Workspace,
    WorkspaceBroker,
    console_exporter,
    jsonl_exporter,
)
from .runtime.permissions import Rule as PermissionRule
from .runtime.router import RouteRule
from .sandboxes import (
    ExecResult,
    Sandbox,
    SandboxWorkspace,
    available_sandboxes,
    register_sandbox,
    sandbox,
)
from .sessions import session_backends, session_provider
from .skills import Skill, SkillRegistry
from .spec import CompiledSpec, SpecCompiler
from .subagents import Bench, SubAgentFactory, SubAgentSpec
from .tools import Tool, ToolContext, ToolRegistry, tool
from .types import (
    Artifact,
    AudioBlock,
    DocumentBlock,
    HandoffRecord,
    ImageBlock,
    Message,
    ModelResponse,
    RunResult,
    Source,
    StreamEvent,
    TextBlock,
    Todo,
    ToolResultBlock,
    ToolUseBlock,
    Usage,
    VideoBlock,
    attach,
)
from .versioning import AgentVersion

__version__ = "0.1.4"

# MCP pulls in the HTTP stack, and most agents never touch it — so it loads on
# first use. `from agent_harness import MCPServer` still works. Governance is
# the same: only those who turn it on pay for importing it.
_LAZY = {"MCPServer": "mcp", "MCPClient": "mcp", "MCPManager": "mcp",
         "MCPAgentServer": "mcp",
         "Governance": "governance", "AgentIdentity": "governance",
         "VoiceAgent": "voice", "RealtimeAgent": "voice", "VoiceEvent": "voice",
         "OpenAISpeech": "voice", "EnergyVAD": "voice",
         # Workflows compile their conditions with the policy expression
         # language, which lives with governance.
         "Workflow": "workflow", "WorkflowSpec": "workflow",
         "WorkflowResult": "workflow", "WorkflowEvent": "workflow",
         "StepResult": "workflow",
         "A2AServer": "a2a", "A2AClient": "a2a", "RemoteAgent": "a2a",
         "A2AError": "a2a",
         "OpenAPIToolkit": "toolkits.openapi", "openapi_tools": "toolkits.openapi",
         "WebSearch": "toolkits.search", "make_search_tool": "toolkits.search",
         "ImageGenerator": "toolkits.images", "image_tools": "toolkits.images",
         "GeneratedImage": "toolkits.images",
         # A browser is started only by an agent that browses.
         "Browser": "browser", "browser_tools": "browser", "computer_tool": "browser",
         "Computer": "browser", "BrowserComputer": "browser",
         "DesktopComputer": "browser"}


def __getattr__(name: str):
    if name in _LAZY:
        import importlib

        module = importlib.import_module(f".{_LAZY[name]}", __name__)
        value = getattr(module, name)
        globals()[name] = value
        return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(_LAZY))

__all__ = [
    "__version__",
    # core
    "Agent",
    "Orchestrator",
    "Harness",
    "Plan",
    "Task",
    "Review",
    # modes
    "modes",
    "Mode",
    "Todo",
    "Source",
    # sub-agents
    "SubAgentSpec",
    "Handoff",
    "HandoffRecord",
    "AgentVersion",
    "Bench",
    "SubAgentFactory",
    # tools and skills
    "tool",
    "Tool",
    "ToolRegistry",
    "ToolContext",
    "Skill",
    "SkillRegistry",
    # prompts
    "Prompt",
    "PromptLibrary",
    # memory
    "MemoryManager",
    "MemoryStore",
    "MemoryRecord",
    "InMemoryStore",
    "FileStore",
    "UserMemory",
    "SessionMemory",
    "OrchestratorMemory",
    "SubAgentMemory",
    "SemanticMemory",
    "VectorStore",
    "Trace",
    "memory_provider",
    "available_backends",
    "Embedder",
    "HashEmbedder",
    "ProviderEmbedder",
    # providers
    "Provider",
    "AnthropicProvider",
    "OpenAIProvider",
    "GeminiProvider",
    "FakeProvider",
    "BedrockProvider",
    "VertexProvider",
    "VertexGeminiProvider",
    "AzureOpenAIProvider",
    "AzureFoundryProvider",
    "GoogleAuth",
    "OpenAICompatibleProvider",
    "OpenRouterProvider",
    "GroqProvider",
    "TogetherProvider",
    "DeepSeekProvider",
    "MistralProvider",
    "XAIProvider",
    "FireworksProvider",
    "CerebrasProvider",
    "OllamaProvider",
    "LMStudioProvider",
    "VLLMProvider",
    "CompletionRequest",
    "ToolSchema",
    "ModelInfo",
    "get_provider",
    "register_provider",
    "register_model",
    "tool_call",
    "list_llm_providers",
    "describe_llm_provider",
    "check_llm_provider",
    "ping_llm_provider",
    "ProviderSpec",
    "ProviderField",
    "ProviderCheck",
    "ParameterPlan",
    "validate_parameters",
    "RetryPolicy",
    "RetryEvent",
    "CircuitBreaker",
    # mcp
    "MCPServer",
    "MCPClient",
    "MCPManager",
    "MCPAgentServer",
    # governance
    "Governance",
    "AgentIdentity",
    # evaluation
    "Evaluator",
    "GoldenTask",
    "Expect",
    "EvalReport",
    "TaskOutcome",
    "Comparison",
    "llm_judge",
    # spec compilation
    "SpecCompiler",
    "CompiledSpec",
    "Blueprint",
    "AgentEntry",
    # guardrails
    "AgentGuardrails",
    "CompletionContext",
    "Violation",
    "Check",
    "RequireTools",
    "ForbidTools",
    "MustInclude",
    "MustNotInclude",
    "MustMatch",
    "MinLength",
    "MaxSteps",
    "MaxCost",
    "RequireCitation",
    "RequireJSON",
    "RequireStructured",
    "NoPlaceholders",
    "Custom",
    "NoPII",
    "NoSecrets",
    "NoInjection",
    "NotToxic",
    "NoRepetition",
    "Grounded",
    "DetectorCheck",
    "PIIDetector",
    "SecretDetector",
    "InjectionDetector",
    "ToxicityDetector",
    "GroundednessDetector",
    "RepetitionDetector",
    "Finding",
    "LLMGuard",
    "LLMVerdict",
    "POLICIES",
    # runtime rails
    "Budget",
    "BudgetGuard",
    "RateLimit",
    "RateGuard",
    "StopController",
    "StopState",
    "AuditTrail",
    "AuditEntry",
    "ServiceHealth",
    "ComponentHealth",
    "DeliverableStore",
    "Replayer",
    "RecordingProvider",
    "ReplayProvider",
    "PolicyGate",
    "PermissionRule",
    "HookEngine",
    "HookContext",
    "Guardrails",
    "Tracer",
    "Span",
    "console_exporter",
    "jsonl_exporter",
    "RunJournal",
    "ResultCache",
    "ConcurrencyScheduler",
    "ModelRouter",
    "RouteRule",
    "Session",
    "SessionStore",
    "DurableSessionStore",
    "InMemorySessionStore",
    "FileSessionStore",
    "session_provider",
    "session_backends",
    "SessionConflict",
    "Checkpoint",
    "Checkpointer",
    "Workspace",
    "WorkspaceBroker",
    # sandboxes
    "sandbox",
    "Sandbox",
    "SandboxWorkspace",
    "ExecResult",
    "register_sandbox",
    "available_sandboxes",
    # context
    "ContextAssembler",
    "ContextCompactor",
    "estimate_tokens",
    # types
    "Message",
    "ModelResponse",
    "RunResult",
    "StreamEvent",
    "Usage",
    "Artifact",
    "attach",
    "ImageBlock",
    "AudioBlock",
    "VideoBlock",
    "DocumentBlock",
    # voice
    "VoiceAgent",
    "RealtimeAgent",
    "VoiceEvent",
    "OpenAISpeech",
    "EnergyVAD",
    "TextBlock",
    "ToolUseBlock",
    "ToolResultBlock",
    # errors
    "HarnessError",
    "ConfigurationError",
    "ProviderError",
    "RateLimitError",
    "QuotaExceededError",
    "AuthenticationError",
    "InvalidRequestError",
    "ModelNotFoundError",
    "ContextWindowExceededError",
    "ProviderTimeoutError",
    "ProviderConnectionError",
    "ProviderUnavailableError",
    "ToolError",
    "ToolNotFound",
    "WorkflowError",
    "Workflow",
    "WorkflowSpec",
    "WorkflowResult",
    "WorkflowEvent",
    "StepResult",
    "A2AServer",
    "A2AClient",
    "RemoteAgent",
    "A2AError",
    "OpenAPIToolkit",
    "openapi_tools",
    "WebSearch",
    "make_search_tool",
    "ImageGenerator",
    "image_tools",
    "GeneratedImage",
    "Browser",
    "browser_tools",
    "computer_tool",
    "Computer",
    "BrowserComputer",
    "DesktopComputer",
    "PermissionDenied",
    "BudgetExceeded",
    "GuardrailTripped",
    "MaxStepsExceeded",
    "OutputContractError",
    "StopRequested",
    "MCPError",
]
