"""Telling people it is AI, and marking what AI made.

Two duties recur across the EU AI Act (Art 50), China's labeling measures and
GB 45438-2025, Korea's AI Basic Act, Vietnam's AI law and DIFC Regulation 10:

* **Disclosure** — the person should know they are dealing with an AI system.
  `result.disclosure` carries the notice, in the languages your packs call
  for; your interface decides where to show it.
* **Marking** — generated content should carry a machine-readable mark.
  `result.provenance` is a manifest in the shape C2PA assertions and GB 45438
  implicit labels both need: who generated it, with what, when, a content id
  and a hash of the content. Signed when the governance layer has a signer.

`label_output=True` (the China pack sets it) also puts a visible label in the
text itself.
"""

from __future__ import annotations

import hashlib
import time
from typing import Any

from pydantic import BaseModel, Field

from ..types import new_id

__all__ = ["DISCLOSURES", "LABELS", "JURISDICTION_LANGUAGE", "disclosure", "label",
           "ProvenanceManifest"]

#: "This response was generated by an AI system."
DISCLOSURES: dict[str, str] = {
    "en": "This response was generated by an AI system.",
    "ar": "تم إنشاء هذا الرد بواسطة نظام ذكاء اصطناعي.",
    "zh": "本回复由人工智能生成。",
    "ko": "이 응답은 인공지능(AI)이 생성했습니다.",
    "ja": "この回答はAIによって生成されました。",
    "vi": "Phản hồi này được tạo bởi trí tuệ nhân tạo (AI).",
    "hi": "यह उत्तर एक कृत्रिम बुद्धिमत्ता (AI) प्रणाली द्वारा तैयार किया गया है।",
    "fr": "Cette réponse a été générée par un système d'intelligence artificielle.",
    "de": "Diese Antwort wurde von einem KI-System erzeugt.",
    "es": "Esta respuesta ha sido generada por un sistema de inteligencia artificial.",
    "it": "Questa risposta è stata generata da un sistema di intelligenza artificiale.",
    "pt": "Esta resposta foi gerada por um sistema de inteligência artificial.",
    "nl": "Dit antwoord is gegenereerd door een AI-systeem.",
    "tr": "Bu yanıt bir yapay zekâ sistemi tarafından oluşturulmuştur.",
    "id": "Respons ini dihasilkan oleh sistem kecerdasan buatan (AI).",
    "ms": "Respons ini dijana oleh sistem kecerdasan buatan (AI).",
    "th": "คำตอบนี้สร้างขึ้นโดยระบบปัญญาประดิษฐ์ (AI)",
}

#: Short visible labels for `label_output`.
LABELS: dict[str, str] = {
    "en": "[AI-generated]", "zh": "【AI生成】", "ar": "[مُنشأ بالذكاء الاصطناعي]",
    "ko": "[AI 생성]", "ja": "[AI生成]", "vi": "[Do AI tạo]", "fr": "[Généré par IA]",
    "de": "[KI-generiert]", "es": "[Generado por IA]",
}


def disclosure(languages: list[str]) -> dict[str, str]:
    """The notice in every requested language we have, English always included."""
    wanted = list(dict.fromkeys(["en", *languages]))
    return {lang: DISCLOSURES[lang] for lang in wanted if lang in DISCLOSURES}


#: The language a label is written in, by the reader's jurisdiction.
JURISDICTION_LANGUAGE: dict[str, str] = {
    "cn": "zh", "kr": "ko", "jp": "ja", "vn": "vi", "sa": "ar", "ae": "ar", "ae-difc": "ar",
    "ae-adgm": "ar", "qa": "ar", "bh": "ar", "om": "ar", "kw": "ar", "fr": "fr", "de": "de",
    "es": "es",
}


def label(text: str, languages: list[str]) -> str:
    """Prefix a visible label, once. Uses the first language with a label."""
    for lang in [*languages, "en"]:
        tag = LABELS.get(lang)
        if tag:
            return text if text.startswith(tag) else f"{tag} {text}"
    return text


class ProvenanceManifest(BaseModel):
    """A machine-readable record that content was AI-generated, and how."""

    content_id: str = Field(default_factory=lambda: new_id("cnt"))
    content_sha256: str = ""
    ai_generated: bool = True
    generator: str = "agent-harness-adk"
    service_provider: str = ""        # the deploying organisation (GB 45438)
    agent: str = ""
    models: list[str] = Field(default_factory=list)
    providers: list[str] = Field(default_factory=list)
    run_id: str = ""
    created: float = Field(default_factory=time.time)
    policy: str = ""
    labels: dict[str, Any] = Field(default_factory=dict)
    signature: str = ""
    key_id: str = ""

    @classmethod
    def for_output(cls, text: str, **fields: Any) -> ProvenanceManifest:
        return cls(content_sha256=hashlib.sha256(text.encode()).hexdigest(), **fields)

    def payload(self) -> bytes:
        return self.model_dump_json(exclude={"signature", "key_id"}).encode()

    def sign(self, signer: Any) -> ProvenanceManifest:
        self.signature = signer.sign(self.payload())
        self.key_id = signer.key_id
        return self

    def verify(self, signer: Any, text: str | None = None) -> bool:
        if text is not None and hashlib.sha256(text.encode()).hexdigest() != \
                self.content_sha256:
            return False
        return bool(self.signature) and signer.verify(self.payload(), self.signature)
